### ISSUE TITLE
  installation of package ‘mdthemes’ had non-zero exit status

### ISSUE THREAD

**Issue by jaum20** [thomas-neitmann/mdthemes#8]
I'm trying to install mdthemes but got through an infinite loop of missing dependencies. First I get:

`ERROR: dependencies ‘hrbrthemes’, ‘tvthemes’ are not available for package ‘mdthemes’`

So I tried to install them

```
installation of package ‘tvthemes’ had non-zero exit status
ERROR: dependency ‘gdtools’ is not available for package ‘hrbrthemes’
```
and

```
installation of package ‘systemfonts’ had non-zero exit status
ERROR: dependency ‘systemfonts’ is not available for package ‘gdtools’
```

Any way to install the dependencies all at once?

**Comment by thomas-neitmann** [comment]
What's your `sessionInfo()`?

Have you tried installing the missing dependencies one by one before attempting to instal {mdthemes}?

**Comment by jaum20** [comment]
Looks like my system is missing `libfontconfig1-dev`,` libcairo2-dev` and `libmagick++-dev`, but I can't install `libmagick++-dev` due to unmet dependencies

**Comment by thomas-neitmann** [comment]
Not an issue if {mdthemes} then. Closing this but hope you can find a workaround. ALso take a look at {ggtext} which underpins the functionality provided by {mdthemes}.
