### ISSUE TITLE
coord_polar bug

### ISSUE THREAD

**Issue by kokkytos** [thomas-neitmann/mdthemes#9]
When I create a pie chart  with `coord_polar` I get:

```
Error in grid.Call.graphics(C_setviewport, vp, TRUE) : 
  non-finite location and/or size for viewport
```

Probably it is related with a [ggtext issue ](https://github.com/wilkelab/ggtext/issues/42)

**Comment by thomas-neitmann** [comment]
If it's an issue with {ggtext} then there's nothing I can do on my side here.
